apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "instancez.fullname" . }}-config
  labels:
    {{- include "instancez.labels" . | nindent 4 }}
data:
  instancez.yaml: |
    {{- .Values.config | nindent 4 }}
