apiVersion: v1
kind: Service
metadata:
  name: {{ include "instancez.fullname" . }}
  labels:
    {{- include "instancez.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "instancez.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
