// Generates src/scripts.generated.js from install.sh and install.ps1.
//
// The scripts are stored base64-encoded so the `wrangler deploy` upload does
// not contain the literal "curl | sh" / "irm | iex" patterns. Cloudflare's WAF
// on api.cloudflare.com blocks those as remote-code-execution signatures, even
// though they are exactly what an installer is supposed to print. deploy.sh
// runs this before wrangler so the generated file is always in sync.
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const here = dirname(fileURLToPath(import.meta.url))
const b64 = (file) => readFileSync(join(here, file)).toString('base64')

const out = `// Generated by gen.mjs. Do not edit by hand; edit install.sh / install.ps1.
export const installShB64 = ${JSON.stringify(b64('install.sh'))}
export const installPs1B64 = ${JSON.stringify(b64('install.ps1'))}
`

writeFileSync(join(here, 'src', 'scripts.generated.js'), out)
console.log('wrote src/scripts.generated.js')
